### PR TITLE
fix copying directories

### LINKED ISSUE #2: Ability to copy everything from a source folder to destination path/folder
I tried passing the path as traditional "path/to/folder/*" to get every file in a folder but it does not work. This feature can come handy when you have many files in source folder.

### PR DESCRIPTION
**Pull request by afirth**
/fixes #2

### CODE REVIEW

**Comment by afirth** [comment]
with this change the syntax for folder to folder is very specific:
```
          WORKFLOW_FILES: |
            github-actions/k8s/.=.github/workflows
```
note the trailing `.` . otherwise you get destination = `.github/workflows/k8s/<file>`

**Comment by artyom-p** [comment]
Hi, when will that be merged?

File: src/index.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ async function run() {
 					let cp_options    = ( is_dir ) ? { recursive: true, force: true } : {},
 						iscopied      = true,
 						dest_basepath = toolkit.path.dirname( `${local_path}${workflow_file.dest}` ),
-						copy_source   = ( is_dir ) ? `${toolkit.path.trailingslashit( source_path )}.` : source_path;
```
Comment (varunsridharan) [inline src/index.js:99]: i added this line to make sure that i can copy files / folder if folder & file exists with the same name.

So it would be nice if you can create a workaround by adding if conditions

Comment (afirth) [reply src/index.js:99]: Sorry, I am not a javascript person. You are welcome to use this code and branch to another PR! I am unclear how to solve #2 with the `\.` without removing this

**Comment by afirth** [comment]
> Hi, when will that be merged?

Due to some changes in dependencies, specifically [importing octokit directly instead of toolkit](https://github.com/FATMAP/action-github-workflow-sync/pull/2/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27-R29) (because [toolkit](https://github.com/actions/toolkit) is not being updated), and the lack of activity on this repo, we are just going to keep our fork going for the bits we use in production and not try to get everything merged back in here, since these are breaking changes to the interface and possibly bits we don't use. If this repo is actively maintained and the maintainers want to pull back in, :100:.

@artyom-p  You can use the forked action @ 8552d87 if you need it.

Thanks so much @varunsridharan for the useful piece of tooling.

**Comment by varunsridharan** [comment]
@afirth

Sorry about the delay. i had some personal issue and the notification for this issue was not on top of my email list. it some how slipped. !!

And thanks for your pull request. i have merged but haven't tested it myself yet. 

I will be looking more into it and will be updating this Github Action in coming days
